// documentation: https://httpyac.github.io/guide/installation_cli.html#arguments


###
GET / HTTP/1.1
Host: localhost:3000

###
GET /_data HTTP/1.1
Host: localhost:3000

###

GET /api/iphone/ HTTP/1.1
Host: www.vpngate.net

// https://allorigins.win/
/*
fetch(`https://api.allorigins.win/get?url=${encodeURIComponent('http://www.vpngate.net/api/iphone/')}`)
.then(response => {
	if (response.ok) return response.json()
	throw new Error('Network response was not ok.')
})
.then(data => console.log(data.contents));
*/

###
@api=http://www.vpngate.net/api/ipho_ne/

GET /get?url={{api}} HTTP/1.1
Host: api.allorigins.win
